language: python

python:
  - "2.7"
  - "3.3"
build_image: shippable/minv2
# command to install dependencies
install:
    - "pip install -r requirements.txt --use-mirrors"
# database creation
before_script:
  - echo $foo and $work
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
  - psql -f test_data.sql -U postgres -d travis_postgis


# command to run tests
script: nosetests --verbose
matrix:
  allow_failures:
    - python: 3.3
    

notifications:
     email:
         recipients:
             - vidya@shippable.com
             - buildsampletest@gmail.com
         on_success: always
         on_failure: always



#cache: true
